import { Montserrat } from "next/font/google";

import "./globals.css";

export const title = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const text = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={title.className}>{children}</body>
    </html>
  );
}
